# Generated by Django 5.1 on 2024-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_choices', models.CharField(choices=[('Tecnico', 'tecnico'), ('Catador', 'catador'), ('Barista', 'barista')], max_length=100)),
            ],
        ),
    ]
