# Generated by Django 5.1 on 2024-10-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
        ('user', '0002_user_fkrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fkrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rol.rol'),
        ),
    ]
