# Generated by Django 5.1 on 2024-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_cedula_user_edad_alter_user_fkrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
